### ISSUE TITLE
Planning conditions & constraints

### ISSUE THREAD

**Issue by colmjude** [digital-land/data-standards-backlog#4]
# Planning conditions & constraints

Some planning applications are "granted with conditions" - these conditions become restrictions on what development can be done to a property/site.

## What 

We are running a mini data discovery to find out more about planning conditions and what people need from the data.

## Why

When someone wants to develop a property or site, it is important to know if any existing planning conditions need to be considered. Having planning conditions as data would allow software providers to build this check into their offering.

## What we're looking for

We want to know more about:

* the planning conditions process - how are conditions created and what is the decision-making process that is used to add them to a planning application?
* what do planning conditions look like? Are they consistent across the country or do there differ from local authority to local authority?
* what are the characteristics of planning conditions? Are they timebound?
* what do people want to do with the data?
* what should be part of the data?
* does any data exist at the moment?
* anything else we need to know

**Comment by debsboyd** [comment]
**What are we learning about conditions?**
We have spoken to three local authorities to date to explore their experiences and processes with planning conditions. An emerging theme is that planning conditions are complex and there is no standardised practice across local authorities currently. Some of the main user needs for standardisations include:

- Help to streamline back end administration
- Making data more readily available
- Readable and accessible

Each local authority we have spoken to so far has presented their own challenges with the organisation of conditions. The main concerns I’ve noted have been:

1. Exploring the possibility of categorising conditions so that they can be coded as they are not currently standardised across LPA’s
2. How ready would other LPAs be to adopt a standard?
3. Variations - in essence, amendments can be made to the original planning application. This creates a need for additional resources and processing stages which can cause difficulties in tracking conditions if not effectively monitored. This is a big aspect to conditions and my thoughts are that it will be the most complex problem to solve.
4. What would be an agreed start date for collating historic data on conditions?
5. How can we incorporate conditions that have been set through the appeals process, would this create further challenges in the standardisation conversation?

**Comment by RichLimbrick** [comment]
@debsboyd - A useful starting point could be the government [model planning conditions in Circular 11/95](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/7715/324923.pdf#page=37) (the rest of the circular has been cancelled but Appendix A remains). They haven't been updated for ages though so keep that in mind.

On point 5, PINS also used to have an extensive list of model conditions and this [Planning Inspectorate suite of suggested conditions](https://www.whatdotheyknow.com/request/398986/response/969448/attach/5/Conditions%20TM%20list%20England%2025%20February%202016.pdf) from 2016 was released under a [PINS FOI request in 2017](https://www.whatdotheyknow.com/request/inspectors_handbook) - there may be more up to date versions now.
